### PR TITLE
NVIDIA repo addition

### PR DESCRIPTION
**Pull request by lkocman**
* Implements #28 
* Add nvidia repoindexes
* Introduce with_nvidia
* Build it only on i586, x86_64, aarch64 (limit is 3rd party repo availability)
* Ensure that migration from Leap 15.X / LeapMicro to TW/MicroOS/Leap16 works as expected
* Provide hw Supplements for all NVIDIA cards

### CODE REVIEW

**Comment by lkocman** [comment]
Built in https://build.opensuse.org/package/show/home:lkocman:branches:Base:System/openSUSE-repos

**Comment by lkocman** [comment]
Tested on Leap 15.5 and TW (x86_64)
https://paste.opensuse.org/pastes/0a5a829cf9ed

**Comment by lkocman** [comment]
> I think probably we should limit it to NVIDIA device only by set hardware supplements

That doesn't sound bad. Current idea was an explicit installation of the package e.g. `zypper in openSUSE-release-Leap-NVIDIA`

**Comment by sndirsch** [comment]
> > I think probably we should limit it to NVIDIA device only by set hardware supplements
> 
> That doesn't sound bad. Current idea was an explicit installation of the package e.g. `zypper in openSUSE-release-Leap-NVIDIA`

I can help with that. Add this to specfile:

`Supplements:    modalias(pci:v000010DEd*sv*sd*bc03sc*i*)`

With that it will be autoselected on all systems with NVIDIA graphics card.

**Comment by lkocman** [comment]
> > > I think probably we should limit it to NVIDIA device only by set hardware supplements
> > 
> > 
> > That doesn't sound bad. Current idea was an explicit installation of the package e.g. `zypper in openSUSE-release-Leap-NVIDIA`
> 
> I can help with that. Add this to specfile:
> 
> `Supplements: modalias(pci:v000010DEd*sv*sd*bc03sc*i*)`
> 
> With that it will be autoselected on all systems with NVIDIA graphics card.

Many thanks @sndirsch

**Comment by lkocman** [comment]
Installation (on my nvidia machine) and build of the latest change tested. Merging. Thank you @nilxam @sndirsch

**Pull request merged**
